Added Support for keys with array values
gwer/oncogene pull request #12
Opened 2017-05-02 19:57 UTC by awebdeveloper

Now array values are supported in which case value will get pushed to the array. This(push) can be overridden to replace in either of the two case.

1. By setting replace: true on a step
2. By setting replace: true on a step variant

2017-05-02 22:15 UTC, gwer requested changes
I think the replacement should be default behaviour. 

What if we will not using `replace` flag? What about something like boolean `push` inside variants[]? Not in steps[].

If the old value is an array, the selected value will be pushed into it. If the old value is not exists, the selected value will be wrapped into an array and added to the config. If the old value is not an array, it will be replaced with the selected value wrapped into an array. If the selected variant has no `push` flag, it always will replace the old value. 

What do you think about it?

2017-05-02 22:15 UTC, gwer commented on oncogene.js
> +    setVal(key, value, selectedVarient, step) {
You can use `this.getStep()` instead of passing step argument.

2017-05-03 03:43 UTC, awebdeveloper commented
Makes sense. I will instead add push: true.

Push can be a value of both varietal and step too so as to allow a variety of cases. I could explain further if you have doubts


Will look into getStep()

2017-05-03 06:09 UTC, awebdeveloper commented
Changes done

2017-05-03 08:45 UTC, gwer commented
If `options.steps[].push === true` and `options.steps[].variants[].push === false` then new value will be pushed into array? But `options.steps[].variants[].push` has greater specificity...

Let's leave only one thing. I vote for `options.steps[].variants[].push` because it's more flexible. I think adding a flag to each variant is not a big problem.

2017-05-03 09:40 UTC, awebdeveloper commented
k done

2017-05-03 09:42 UTC, gwer approved these changes

2017-05-03 09:42 UTC, gwer commented
Looks fine. Thanks.

2017-05-03 09:43 UTC, merged