Showif
gwer/oncogene pull request #17
Opened 2017-05-03 19:12 UTC by awebdeveloper

Implements showIf callback method. Should fix #10 

ps: just review the code. I will update this pr to fix merge issues(if any) once you merge other one or vice versa

2017-05-03 20:03 UTC, gwer requested changes

2017-05-03 20:03 UTC, gwer commented on oncogene.js
> +           return this.nextStep();
stepSize can be negative. So we need `this.nextStep(stepSize)` instead of `this.nextStep()`.

2017-05-04 03:10 UTC, awebdeveloper commented on oncogene.js
> +           return this.nextStep();
Sorry can you explain why

2017-05-04 03:14 UTC, awebdeveloper commented on oncogene.js
> +           return this.nextStep();
nextStep has no parameter

2017-05-04 08:14 UTC, gwer commented on oncogene.js
> +           return this.nextStep();
I'm sorry, `this.makeStep(stepSize)` of course.

2017-05-04 09:34 UTC, awebdeveloper commented on oncogene.js
> +           return this.nextStep();
sorry i still dont get it

2017-05-04 09:42 UTC, gwer commented on oncogene.js
> +           return this.nextStep();
`this.nextStep()` is an alias for `this.makeStep(1)`. Oncogene's API allows you to call `this.makeStep(-1)` or `this.prevStep()`.

If you want to go back to the previous step, and the previous step shouldn't be showed, you should go back, not forward.

2017-05-04 11:24 UTC, awebdeveloper commented
done

2017-05-04 11:26 UTC, merged

2017-05-04 11:26 UTC, gwer commented
Thanks